#!/bin/bash

pyenv install --skip-existing

#VENV="${PWD##*/}.venv"
VENV="venv"
VENV=${VENV#-}
python -m venv $VENV
. $VENV/bin/activate
# python -m pip install -U pip wheel
python -m pip install -r requirements.txt
