#!/bin/bash

pyenv install --skip-existing

VENV="${PWD##*/}.venv"
VENV=${VENV#-}
python3 -m venv $VENV
. $VENV/bin/activate
python3 -m pip install -U pip wheel
python3 -m pip install -r requirements.txt
